# Generated by Django 5.2.5 on 2025-08-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField()),
                ('lastname', models.CharField()),
                ('age', models.PositiveIntegerField()),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
